nfl_dead_money:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: nfl_dead_money_dev
      threads: 4
      location: US
      timeout_seconds: 300
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: nfl_dead_money
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"
      threads: 4
      location: US
      timeout_seconds: 300

