-- Migration: 001_enforce_append_only_ledger
-- Description: No-op (originally DuckDB/MotherDuck RBAC — not applicable to BigQuery)
--
-- The original migration used CREATE ROLE / GRANT / REVOKE which are DuckDB-only
-- syntax not supported by BigQuery. BigQuery IAM handles access control at the
-- dataset/table level via GCP IAM bindings, not SQL ROLE statements.
--
-- This file is intentionally a no-op so the idempotent migration runner can record
-- it as applied and stop retrying.
