-- Migration: 009_enforce_core_identity_constraints
-- Issue: #106 — SP29-1: Enforce strict BigQuery NOT NULL constraints
--
-- CONVERTED TO NO-OP: BigQuery does not support ALTER COLUMN ... SET NOT NULL
-- via the standard SQL jobs API (syntax error: expected DATA, DEFAULT, GENERATED,
-- or OPTIONS). NOT NULL enforcement is handled at the application layer by
-- pipeline/src/data_quality_tests.py::validate_not_null_constraints().
--
-- Original intent: enforce NOT NULL on identity columns across
--   silver_pfr_game_logs, silver_penalties, silver_spotrac_contracts,
--   silver_spotrac_rankings, silver_team_cap, silver_player_metadata,
--   silver_team_finance, silver_spotrac_salaries, silver_pfr_draft_history,
--   fact_player_efficiency
SELECT 1;
