-- Migration 009: Schema Integrity — NOT NULL Constraints (Issue #106)
--
-- CONVERTED TO NO-OP: BigQuery does not support ALTER COLUMN ... SET NOT NULL
-- via the standard SQL jobs API (syntax error: expected DATA, DEFAULT, GENERATED,
-- or OPTIONS). NOT NULL enforcement is handled at the application layer by
-- pipeline/src/data_quality_tests.py::validate_not_null_constraints().
--
-- Original intent: enforce NOT NULL on identity columns across
--   bronze_sportsdataio_players, fact_player_efficiency,
--   silver_spotrac_contracts, raw_pundit_media
-- Those tables are validated at pipeline runtime, not at schema level.
SELECT 1;
