import React from "react";
import { Metadata } from "next";
import Link from "next/link";
import { ShieldAlert, ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
    title: "Terms of Service | Pundit Ledger",
    description: "Terms of service for Pundit Ledger.",
};

export default function TermsOfService() {
    return (
        <main className="min-h-[100dvh] bg-black text-white px-6 py-16">
            <div className="max-w-3xl mx-auto">
                {/* Back link */}
                <Link
                    href="/"
                    className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-zinc-300 transition-colors mb-10"
                >
                    <ArrowLeft className="w-4 h-4" />
                    Back to Pundit Ledger
                </Link>

                {/* Header */}
                <div className="flex items-center gap-3 mb-2">
                    <ShieldAlert className="w-7 h-7 text-emerald-400 shrink-0" />
                    <h1 className="text-3xl font-extrabold tracking-tight">Terms of Service</h1>
                </div>
                <p className="text-sm text-zinc-500 mb-12">Last Updated: April 27, 2026</p>

                {/* Body */}
                <div className="space-y-10 text-zinc-300 leading-relaxed">
                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-white">
                            1. For Entertainment and Informational Purposes Only
                        </h2>
                        <p>
                            Pundit Ledger (&quot;The Service&quot;) — including its prediction
                            tracking, accuracy scores, Brier scores, and Pundit Credit Scores —
                            is provided for <strong>entertainment and informational purposes
                            only.</strong>
                        </p>
                        <p className="text-rose-400 font-semibold">
                            UNDER NO CIRCUMSTANCES should the scores or rankings generated by
                            this application be construed as financial, legal, or professional
                            sports-betting advice.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-white">
                            2. Limitation of Liability
                        </h2>
                        <p>
                            You agree that the operators, developers, and affiliated entities of
                            The Service shall not be held liable for any decisions — financial or
                            otherwise — made based on data, scores, or predictions presented
                            herein. The Service cannot guarantee the accuracy, completeness, or
                            timeliness of its data.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-white">
                            3. Intellectual Property
                        </h2>
                        <p>
                            The scoring methodology, source code, and branding
                            (&quot;Pundit Ledger&quot;) are proprietary intellectual property.
                            You may not scrape, reverse-engineer, redistribute, or commercially
                            syndicate data from this platform without an explicit written license.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-white">
                            4. Payment and Subscription
                        </h2>
                        <p>
                            Certain Pro features require an active subscription. By providing
                            payment information, you authorise our third-party payment processor
                            (Stripe) to charge the applicable fees. Subscriptions automatically
                            renew unless cancelled prior to the billing cycle.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-white">
                            5. Data Sources
                        </h2>
                        <p>
                            The Service aggregates data from publicly available sources in
                            accordance with applicable fair-use principles. All tracked
                            predictions are statements made publicly by the pundits themselves.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-white">6. Contact</h2>
                        <p>
                            Questions?{" "}
                            <a
                                href="mailto:support@cap-alpha.co"
                                className="text-emerald-400 hover:text-emerald-300 transition-colors"
                            >
                                support@cap-alpha.co
                            </a>
                        </p>
                    </section>
                </div>

                {/* Footer nav */}
                <div className="mt-16 pt-8 border-t border-zinc-900 flex items-center gap-6 text-xs text-zinc-600">
                    <Link href="/legal/privacy" className="hover:text-zinc-400 transition-colors">
                        Privacy Policy
                    </Link>
                    <Link href="/methodology" className="hover:text-zinc-400 transition-colors">
                        Methodology
                    </Link>
                    <Link href="/ledger" className="hover:text-zinc-400 transition-colors">
                        Leaderboard
                    </Link>
                </div>
            </div>
        </main>
    );
}
