-- AUTO-GENERATED BY contracts/compile.py
-- DO NOT EDIT MANUALLY

-- Raw game logs from Pro-Football-Reference
CREATE TABLE IF NOT EXISTS silver_pfr_game_logs (
    player_name STRING NOT NULL,
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    week INTEGER NOT NULL,
    game_url STRING,
    Passing_Yds STRING,
    Rushing_Yds STRING,
    Receiving_Yds STRING,
    Passing_TD STRING,
    Rushing_TD STRING,
    Receiving_TD STRING,
    Sacks STRING,
    Interceptions STRING
);

-- Player penalty statistics
CREATE TABLE IF NOT EXISTS silver_penalties (
    player_name_short STRING NOT NULL,
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    penalty_count INTEGER,
    penalty_yards INTEGER
);

-- Contract data from Spotrac (SCD Type 2 Ledger)
CREATE TABLE IF NOT EXISTS silver_spotrac_contracts (
    contract_id STRING NOT NULL,
    player_id STRING,
    player_name STRING NOT NULL,
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    position STRING,
    cap_hit_millions FLOAT64 NOT NULL,
    dead_cap_millions FLOAT64,
    signing_bonus_millions FLOAT64,
    guaranteed_money_millions FLOAT64,
    total_contract_value_millions FLOAT64,
    base_salary_millions FLOAT64,
    prorated_bonus_millions FLOAT64,
    roster_bonus_millions FLOAT64,
    guaranteed_salary_millions FLOAT64,
    age INTEGER,
    effective_start_date TIMESTAMP,
    effective_end_date TIMESTAMP,
    is_current BOOLEAN,
    system_ingest_time TIMESTAMP NOT NULL
);

-- Positional ranking data
CREATE TABLE IF NOT EXISTS silver_spotrac_rankings (
    player_name STRING NOT NULL,
    year INTEGER NOT NULL,
    ranking_cap_hit_millions FLOAT64
);

-- Team-level cap and performance data
CREATE TABLE IF NOT EXISTS silver_team_cap (
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    win_pct FLOAT64
);

-- Static player attributes
CREATE TABLE IF NOT EXISTS silver_player_metadata (
    full_name STRING NOT NULL,
    birth_date STRING,
    college STRING,
    draft_round INTEGER,
    draft_pick INTEGER,
    experience_years INTEGER
);

-- NFLPA Merchandise sales rankings
CREATE TABLE IF NOT EXISTS silver_player_merch (
    Player STRING NOT NULL,
    Rank INTEGER
);

-- Forbes team valuation data
CREATE TABLE IF NOT EXISTS silver_team_finance (
    Team STRING NOT NULL,
    Year INTEGER NOT NULL,
    Revenue_M FLOAT64,
    OperatingIncome_M FLOAT64
);

-- Salary breakdown
CREATE TABLE IF NOT EXISTS silver_spotrac_salaries (
    player_name STRING NOT NULL,
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    position STRING,
    dead_cap STRING
);

-- Draft history data
CREATE TABLE IF NOT EXISTS silver_pfr_draft_history (
    player_name STRING NOT NULL,
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    draft_round INTEGER,
    draft_pick INTEGER
);

-- Gold Layer: Player Efficiency Analytics
CREATE TABLE IF NOT EXISTS fact_player_efficiency (
    player_name STRING NOT NULL,
    team STRING NOT NULL,
    year INTEGER NOT NULL,
    position STRING NOT NULL,
    age INTEGER,
    college STRING,
    draft_round INTEGER,
    draft_pick INTEGER,
    experience_years INTEGER,
    games_played INTEGER,
    availability_rating FLOAT64,
    total_pass_yds FLOAT64,
    total_rush_yds FLOAT64,
    total_rec_yds FLOAT64,
    total_tds INTEGER,
    total_penalty_count INTEGER,
    total_penalty_yards INTEGER,
    total_sacks FLOAT64,
    total_int FLOAT64,
    cap_hit_millions FLOAT64 NOT NULL,
    dead_cap_millions FLOAT64,
    signing_bonus_millions FLOAT64,
    guaranteed_money_millions FLOAT64,
    base_salary_millions FLOAT64,
    prorated_bonus_millions FLOAT64,
    roster_bonus_millions FLOAT64,
    guaranteed_salary_millions FLOAT64,
    potential_dead_cap_millions FLOAT64,
    edce_risk FLOAT64,
    fair_market_value FLOAT64,
    ml_risk_score FLOAT64
);
