import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ShieldAlert } from "lucide-react";

export default function TermsOfService() {
    return (
        <main className="min-h-[100dvh] bg-background text-foreground p-8 flex justify-center">
            <Card className="w-full max-w-4xl bg-card border-border shadow-xl">
                <CardHeader className="border-b border-border/50 pb-6 mb-6">
                    <div className="flex items-center gap-4 text-emerald-500 mb-4">
                        <ShieldAlert className="w-8 h-8" />
                        <CardTitle className="text-3xl font-extrabold tracking-tight">Terms of Service</CardTitle>
                    </div>
                    <p className="text-muted-foreground">Last Updated: February 22, 2026</p>
                </CardHeader>
                <CardContent className="space-y-8 text-slate-300 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold text-white mb-2">1. For Entertainment and Educational Purposes Only</h2>
                        <p>
                            The Cap Alpha Protocol (&quot;The Service&quot;), including but not limited to its predictive models, efficiency scores, fair market value algorithms, and suggested roster actions (&quot;Cut&quot;, &quot;Restructure&quot;, &quot;Trade&quot;), is provided strictly for <strong>entertainment, simulation, and educational purposes only.</strong>
                        </p>
                        <p className="mt-2 text-rose-400 font-semibold">
                            UNDER NO CIRCUMSTANCES should the insights generated by this application be construed as professional financial, legal, or sports management advice.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-2">2. Liability Shield: Algorithmic Output</h2>
                        <p>
                            You agree that the operators, developers, and affiliated entities of The Service shall not be held liable for any decisions—professional, financial, or otherwise—made based on the data, simulations, or predictions presented herein. Real-world roster construction involves variables outside the scope of mathematical modeling. The Service cannot be held responsible for the accuracy, completeness, or timeliness of its data.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-2">3. Intellectual Property Rights</h2>
                        <p>
                            The underlying predictive models, methodologies (including but not limited to the Point-in-Time Feature Store and Adversarial Trade Engine), source code, and branding (&quot;Cap Alpha Protocol&quot;) are proprietary intellectual property.
                        </p>
                        <p className="mt-2">
                            You may not scrape, reverse-engineer, redistribute, or commercially syndicate the alpha signals generated by this platform without an explicit Enterprise Data License.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-2">4. Payment and Subscription</h2>
                        <p>
                            Certain features of The Service require an active subscription. By providing payment information, you authorize our third-party payment processor (Stripe) to charge the applicable fees. Subscriptions automatically renew unless canceled prior to the billing cycle. No refunds will be issued for partial terms or generated insights that do not manifest in real-world scenarios.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-2">5. Data Privacy & Third-Party Integrity</h2>
                        <p>
                            The Service aggregates data from publicly available sources in accordance with Fair Use and relevant Terms of Service. By using The Service, you agree that your interaction data may be logged to improve the predictive models.
                        </p>
                    </section>
                </CardContent>
            </Card>
        </main>
    );
}
